# Generated by Django 5.1 on 2024-08-22 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='visited',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 22, 12, 33, 29, 427125, tzinfo=datetime.timezone.utc)),
        ),
    ]
